export const translations = {
  en: {
    home: {
      pageTitle: "Content Bridge",
      pageSubtitle: "Show related WordPress posts on your products automatically.",
      settings: "Settings",

      quickStart: "Quick start",
      qs1Prefix: "Connect WordPress in",
      qs1Suffix: "(endpoint + API key)",
      qs2Prefix: "Configure matching in the theme app block",
      qs2Suffix: "(WordPress taxonomy + store term source)",
      qs3: "Optionally add a WordPress category/tag slug to a product metafield.",
      openSettings: "Open Settings",
      testConnection: "Test connection",

      wpNotConfiguredTitle: "WordPress is not configured yet",
      wpNotConfiguredBody: "Go to Settings and set your endpoint and API key first.",

      status: "Status",
      wpSettingsTitle: "WordPress settings",
      wpSettingsOk: "Endpoint and API key are set.",
      wpSettingsNg: "Set WP endpoint and API key.",
      manage: "Manage",

      productMfTitle: "Product term override",
      mfChecking: "Checking metafield status...",
      mfEnabledProductsSuffix: "is enabled for products.",
      mfEnabledCollectionsSuffix: "is enabled for collections.",
      mfEnableInSettingsPrefix: "Enable",
      mfEnableInSettingsSuffixProducts: "for products in Settings.",
      mfEnableInSettingsSuffixCollections: "for collections in Settings.",

      metaHelpTitle: "Matching term",
      metaHelpBodyPrefix: "Match a WordPress",
      metaHelpBodyMid: "category",
      metaHelpBodyMid2: "tag",
      metaHelpBodySuffix:
        "slug against a store value such as vendor, product type, first tag, first collection handle, or custom term.",

      troubleshooting: "Troubleshooting",
      tr1Prefix: "Make sure the endpoint ends with",
      tr2: "API key must match the WordPress plugin",
      tr3: "If Test connection fails, check firewall / basic auth / maintenance mode",
    },
    settings: {
      pageTitle: "Settings",
      pageSubtitle: "Connect WordPress and configure how product data matches WordPress posts.",
      back: "Back",
      save: "Save",

      refreshingTitle: "Connection is refreshing",
      refreshingBodyPrefix: "Your edits are not saved yet. Please click ",
      refreshingBodyMid: "Save",
      refreshingBodySuffix: " first, or reload after saving.",
      reload: "Reload",

      unknownError: "Unknown error",

      wpCardTitle: "WordPress connection",
      wpCardDesc: "Paste your WordPress endpoint and API key generated by the Content Bridge WP plugin.",

      wpEndpointLabel: "WP Posts Endpoint",
      wpEndpointHelpPrefix: "Example:",
      wpApiKeyLabel: "WP API Key",
      sentAsHeaderPrefix: "Sent as ",
      sentAsHeaderSuffix: " header.",
      hide: "Hide",
      show: "Show",
      testConnection: "Test connection",

      mfCardTitle: "Product term override (optional)",
      mfCardBodyPrefix: "This app can use a dedicated product metafield ",
      mfCardBodySuffix: " (single line text) to override the term source selected in the theme app block.",

      productMfTitle: "Product metafield",

      status: "Status",
      checking: "Checking...",
      enabled: "Enabled",
      notEnabled: "Not enabled",

      enable: "Enable",
      enabledButton: "Enabled",

      checklistTitle: "Quick checklist",
      checklist1Prefix: "Endpoint ends with ",
      checklist1Suffix: "",
      checklist2Prefix: "Endpoint contains ",
      checklist2Suffix: "",
      checklist3: "API key is from the WP plugin settings",

      howTitle: "How matching works",
      howBodyPrefix:
        "Choose whether to match WordPress categories or tags, then choose the product value used as the term: vendor, product type, first tag, first collection handle, or custom term. Product field ",
      howBodySuffix: " is optional and overrides the selected term source when set.",
    },
  },

  ja: {
    home: {
      pageTitle: "Content Bridge",
      pageSubtitle: "商品ページに、関連するWordPress記事を自動で表示します。",
      settings: "設定",

      quickStart: "クイックスタート",
      qs1Prefix: "まず",
      qs1Suffix: "でWordPressのエンドポイントとAPIキーを接続します。",
      qs2Prefix: "テーマアプリブロックで照合設定を行います",
      qs2Suffix: "（WordPressの分類 + ストア側の照合元）",
      qs3: "必要に応じて、商品メタフィールドにWordPressのカテゴリ/タグ slug を設定します。",
      openSettings: "設定を開く",
      testConnection: "接続をテスト",

      wpNotConfiguredTitle: "WordPressがまだ設定されていません",
      wpNotConfiguredBody: "まず設定画面でエンドポイントとAPIキーを入力してください。",

      status: "ステータス",
      wpSettingsTitle: "WordPress設定",
      wpSettingsOk: "エンドポイントとAPIキーが設定されています。",
      wpSettingsNg: "WPエンドポイントとAPIキーを設定してください。",
      manage: "管理",

      productMfTitle: "商品ごとのターム上書き",
      mfChecking: "メタフィールドの状態を確認中...",
      mfEnabledProductsSuffix: "は商品で有効です。",
      mfEnabledCollectionsSuffix: "はコレクションで有効です。",
      mfEnableInSettingsPrefix: "設定で",
      mfEnableInSettingsSuffixProducts: "を商品向けに有効化してください。",
      mfEnableInSettingsSuffixCollections: "をコレクション向けに有効化してください。",

      metaHelpTitle: "照合ターム",
      metaHelpBodyPrefix: "WordPressの",
      metaHelpBodyMid: "カテゴリ",
      metaHelpBodyMid2: "タグ",
      metaHelpBodySuffix:
        "slug を、商品ベンダー、商品タイプ、最初の商品タグ、最初のコレクションhandle、またはカスタムタームと照合します。",

      troubleshooting: "トラブルシューティング",
      tr1Prefix: "エンドポイントの末尾が次で終わっているか確認してください:",
      tr2: "APIキーはWordPressプラグイン側の値と一致している必要があります。",
      tr3: "接続テストに失敗する場合は、ファイアウォール、Basic認証、メンテナンスモードを確認してください。",
    },
    settings: {
      pageTitle: "設定",
      pageSubtitle: "WordPressと接続し、商品データをWordPress記事と照合する方法を設定します。",
      back: "戻る",
      save: "保存",

      refreshingTitle: "接続情報を更新中です",
      refreshingBodyPrefix: "変更内容はまだ保存されていません。先に",
      refreshingBodyMid: "保存",
      refreshingBodySuffix: "をクリックするか、保存後に再読み込みしてください。",
      reload: "再読み込み",

      unknownError: "不明なエラー",

      wpCardTitle: "WordPress接続",
      wpCardDesc: "Content Bridge WPプラグインで生成されたWordPressエンドポイントとAPIキーを貼り付けてください。",

      wpEndpointLabel: "WP投稿エンドポイント",
      wpEndpointHelpPrefix: "例:",
      wpApiKeyLabel: "WP APIキー",
      sentAsHeaderPrefix: "ヘッダー ",
      sentAsHeaderSuffix: " として送信されます。",
      hide: "非表示",
      show: "表示",
      testConnection: "接続をテスト",

      mfCardTitle: "商品ごとのターム上書き（任意）",
      mfCardBodyPrefix: "このアプリでは、専用の商品メタフィールド ",
      mfCardBodySuffix: "（単一行テキスト）を使って、テーマアプリブロックで選択した照合元を上書きできます。",

      productMfTitle: "商品メタフィールド",

      status: "ステータス",
      checking: "確認中...",
      enabled: "有効",
      notEnabled: "未有効",

      enable: "有効化",
      enabledButton: "有効",

      checklistTitle: "クイックチェックリスト",
      checklist1Prefix: "エンドポイントの末尾が ",
      checklist1Suffix: " で終わっている",
      checklist2Prefix: "エンドポイントに ",
      checklist2Suffix: " が含まれている",
      checklist3: "APIキーはWPプラグイン設定で発行されたものを使用している",

      howTitle: "照合の仕組み",
      howBodyPrefix:
        "WordPressのカテゴリまたはタグのどちらと照合するかを選び、照合に使う商品データ（ベンダー、商品タイプ、最初の商品タグ、最初のコレクションhandle、カスタムターム）を選択します。商品フィールド ",
      howBodySuffix: " は任意で、設定されている場合は選択された照合元より優先されます。",
    },
  },
} as const;

export type LocaleKey = keyof typeof translations;
